### PR TITLE
feat: show namespace maintainers and admins list in namespace page.

### PR DESCRIPTION
**Pull request by arteevraina**
- [x] Added API to show the list of namespace admins and maintainers.
- [x] Added the tests for the same.
- [x] Added the UI + actions to show the list of admins and maintainers of the namespace.
- [x] Added the UI + actions for viewing package maintainers.

### CODE REVIEW

**Comment by arteevraina** [comment]
Testable Link - https://registry-frontend-arteevraina.vercel.app/

**Review by henilp105 — APPROVED** [review]
Thanks @arteevraina , Looks good to me.

**Comment by minhqdao** [comment]
Screenshot 2023-05-24 at 13 37 06

**Comment by arteevraina** [comment]
> Screenshot 2023-05-24 at 13 37 06

Hi @minhqdao ,
Thanks for reporting this. 

This is the testing url and there is high chance that your older cookies that were valid for the backend before it was reset. So, can you please clear the cookies for this testing url https://registry-frontend-arteevraina.vercel.app/ as well and see if it is still failing ?

**Comment by minhqdao** [comment]
Where can I see the changes made in this PR? I added a maintainer but I couldn't observe any UI changes on my dashboard.

**Comment by minhqdao** [comment]
Ok, I figured it out. I find it a bit complicated. By adding extra buttons for every new feature? Just list all the maintainers in a vertical list here:

Screenshot 2023-05-24 at 13 47 24

**Comment by minhqdao** [comment]
Also the created date can't be correct. I created the namespace a while ago.

**Comment by arteevraina** [comment]
> Also the created date can't be correct. I created the namespace a while ago.

Should be fixed now.

**Comment by arteevraina** [comment]
> Where can I see the changes made in this PR? I added a maintainer but I couldn't observe any UI changes on my dashboard.

For package maintainers https://registry-frontend-arteevraina.vercel.app/packages/minhdao/version-f you can view package maintainers here.

**Comment by minhqdao** [comment]
Oh, using the button ...

However, sometimes the button appears, sometimes it doesn't. I've seen it once. But now, whatever I do, I can't make it reappear again.

**Comment by minhqdao** [comment]
Oh, I can reproduce it. When you go in via dashboard -> namespace -> package, you see the green button. If you don't follow that particular sequence, you never see the button. That shouldn't be.

**Comment by arteevraina** [comment]
Hey @minhqdao ,

We discussed in the last meeting that show the button when the user is logged in. But, there is one issue with that, so every user that is logged in should be shown the button (for showing package maintainers) or only package maintainers or namespace admins or namespace maintainers ?

**Comment by arteevraina** [comment]
> Hey @minhqdao ,
> 
> We discussed in the last meeting that show the button when the user is logged in. But, there is one issue with that, so every user that is logged in should be shown the button (for showing package maintainers) or only package maintainers or namespace admins or namespace maintainers ?

I would prefer only prefer admins, maintainers or package maintainers to be shown that button but maybe we can show it to every logged in user ?

**Comment by minhqdao** [comment]
Only show the button if the user is logged in and the user is a package maintainer, namespace maintainer or admin etc.

**Comment by arteevraina** [comment]
> Only show the button if the user is logged in and the user is a package maintainer, namespace maintainer or admin etc.

@minhqdao You can verify it [here](https://registry-frontend-arteevraina.vercel.app/packages/minhdao/version-f ).

**Review by minhqdao — APPROVED** [review]
Looks good. 👍🏽

**Pull request merged**
